services:
  redis:
    image: redis:7

  web:
    build:
      context: /www/wwwroot/dashboard.cityhangaround.com/HBD_Dashboard/backend
      dockerfile: Dockerfile
    command: gunicorn app:app -b 0.0.0.0:8000
    ports:
      - "8000:8000"
    volumes:
      - /www/wwwroot/dashboard.cityhangaround.com/HBD_Dashboard/backend/tmp:/app/tmp
    depends_on:
      - redis

  worker:
    build:
      context: /www/wwwroot/dashboard.cityhangaround.com/HBD_Dashboard/backend
      dockerfile: Dockerfile
    command: celery -A celery_app.celery worker --loglevel=info
    volumes:
      - /www/wwwroot/dashboard.cityhangaround.com/HBD_Dashboard/backend/tmp:/app/tmp
    depends_on:
      - redis